# Generated by Django 3.1.2 on 2020-10-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='made_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
