# Generated by Django 3.1.2 on 2020-10-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_candy_made_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candy',
            name='made_by',
        ),
    ]
