# Generated by Django 3.1.2 on 2020-10-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_candy_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candy',
            old_name='user',
            new_name='seller',
        ),
    ]
