# Generated by Django 3.1.2 on 2020-10-31 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.store'),
        ),
    ]
