# Generated by Django 3.1.2 on 2020-10-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201031_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='candy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
